# stopwords.py

english_stopwords = [
    "a", "about", "above", "after", "again", "against", "all", "am", "an", "and",
    "any", "are", "aren't", "as", "at", "be", "because", "been", "before", "being",
    "below", "between", "both", "but", "by", "can", "can't", "cannot", "could",
    "couldn't", "did", "didn't", "do", "does", "doesn't", "doing", "don't", "down",
    "during", "each", "few", "for", "from", "further", "had", "hadn't", "has",
    "hasn't", "have", "haven't", "having", "he", "he'd", "he'll", "he's", "her",
    "here", "here's", "hers", "herself", "him", "himself", "his", "how", "how's",
    "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "isn't", "it",
    "it's", "its", "itself", "let's", "me", "more", "most", "mustn't", "my", "myself",
    "no", "nor", "not", "of", "off", "on", "once", "only", "or", "other", "ought",
    "our", "ours", "ourselves", "out", "over", "own", "same", "shan't", "she", "she'd",
    "she'll", "she's", "should", "shouldn't", "so", "some", "such", "than", "that",
    "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's",
    "these", "they", "they'd", "they'll", "they're", "they've", "this", "those", "through",
    "to", "too", "under", "until", "up", "very", "was", "wasn't", "we", "we'd", "we'll",
    "we're", "we've", "were", "weren't", "what", "what's", "when", "when's", "where",
    "where's", "which", "while", "who", "who's", "whom", "why", "why's", "with", "won't",
    "would", "wouldn't", "you", "you'd", "you'll", "you're", "you've", "your", "yours",
    "yourself", "yourselves"
]

german_stopwords = [
    "aber", "alle", "allem", "allen", "aller", "alles", "als", "also", "am", "an",
    "ander", "andere", "anderem", "anderen", "anderer", "anderes", "anderm", "andern",
    "anderr", "anders", "auch", "auf", "aus", "bei", "bin", "bis", "bist", "da",
    "damit", "dann", "das", "dass", "dasselbe", "dazu", "daß", "dein", "deine", "deinem",
    "deinen", "deiner", "deines", "dem", "demselben", "den", "denn", "denselben", "der",
    "derer", "derselbe", "derselben", "des", "deshalb", "desselben", "dessen", "dich",
    "die", "dies", "diese", "diesem", "diesen", "dieser", "dieses", "dir", "doch", "dort",
    "du", "durch", "ein", "eine", "einem", "einen", "einer", "eines", "einige", "einigem",
    "einigen", "einiger", "einiges", "einmal", "er", "es", "etwas", "euch", "euer", "eure",
    "eurem", "euren", "eurer", "eures", "für", "gegen", "gewesen", "hab", "habe", "haben",
    "hat", "hatte", "hatten", "hattest", "hattet", "hier", "hin", "hinter", "ich", "ihm",
    "ihn", "ihnen", "ihr", "ihre", "ihrem", "ihren", "ihrer", "ihres", "im", "in", "indem",
    "ins", "ist", "jede", "jedem", "jeden", "jeder", "jedes", "jener", "jenes", "jetzt",
    "kann", "kein", "keine", "keinem", "keinen", "keiner", "keines", "können", "könnte",
    "machen", "man", "manche", "manchem", "manchen", "mancher", "manches", "mein", "meine",
    "meinem", "meinen", "meiner", "meines", "mich", "mir", "mit", "muss", "musste", "nach",
    "nachdem", "nein", "nicht", "nichts", "noch", "nun", "nur", "ob", "oder", "ohne", "sehr",
    "sein", "seine", "seinem", "seinen", "seiner", "seines", "selbst", "sich", "sie", "sind",
    "so", "solche", "solchem", "solchen", "solcher", "solches", "soll", "sollte", "sondern",
    "sonst", "über", "um", "und", "uns", "unser", "unsere", "unserem", "unseren", "unserer",
    "unseres", "unter", "viel", "vom", "von", "vor", "wann", "war", "waren", "warst", "was",
    "weg", "weil", "weiter", "welche", "welchem", "welchen", "welcher", "welches", "wenn",
    "wer", "werde", "werden", "werdet", "weshalb", "wie", "wieder", "will", "wir", "wird",
    "wirklich", "wo", "wollen", "wollte", "wurde", "wurden", "zu", "zum", "zur", "zwar", "zwischen"
]
